Animation
ntut-open-source-club/practical-tools-for-simple-design pull request #108
Opened 2024-02-13 17:49 UTC by NOOBDY

2024-02-21 17:46 UTC, Error0229 reviewed
+ Some debug message may cleared.
+ Animation state's getter aren't complete.
+ However most of given API works fine.

2024-02-21 17:46 UTC, Error0229 commented on src/Core/Context.cpp
>  }
The `Util::Time::GetDeltaTime()` is getting the delta time between "last frame start time" and "current frame start time", Which is not the delta time between "current frame start" and the moment "this function got called". Which cause it always Delay for wrong period.

2024-02-21 17:46 UTC, Error0229 commented on include/Util/Animation.hpp
> +     * @param bool Whether the animation should play right away.
`@param play`

2024-02-22 03:00 UTC, NOOBDY commented on src/Util/Animation.cpp
> +        m_LastFrameStartTime = Util::Time::GetElapsedTimeMs();
it gets the job done, also I can't come up with a better name

2024-02-22 03:46 UTC, NOOBDY commented on src/Util/Animation.cpp
> +        }
i feel like the implementation here is fucked

2024-02-22 04:19 UTC, Dragonfly911117 requested changes
Seems good to me except some minor changes needed.

2024-02-22 04:19 UTC, Dragonfly911117 commented on include/Util/Time.hpp
> +    static void StartCounter() { s_Start = SDL_GetPerformanceCounter(); }
Need docs for this method. Also, what the purpose of this method? `s_Start` already inited with `SDL_GetPerformanceCounter()`.

2024-02-22 04:19 UTC, Dragonfly911117 commented on include/Util/Time.hpp
> +    static unsigned long GetElapsedTimeMs();
Need docs for this method.

2024-02-22 04:19 UTC, Dragonfly911117 commented on include/Util/Time.hpp
> +    static unsigned long GetElapsedTimeMs();
```suggestion
    /**
     * @brief Get the elapsed time from the start of the program in
     * milliseconds.
     *
     * @note To create a timer, one may call this function to record the time,
     * and then call it again to obtain the time difference.
     *
     * @return The elapsed time from the start of the program in milliseconds.
     */
    static unsigned long GetElapsedTimeMs();```

2024-02-22 04:19 UTC, Dragonfly911117 commented on src/Core/Context.cpp
> +    }
Having `FPS_CAP` as `0` triggers "Constexpr variable 'frameTime' must be initialized by a constant expression division by zero". error. 
```suggestion
constexpr double frameTime =
        FPS_CAP != 0 ? 1000 / static_cast<double>(FPS_CAP) : 0;
    SDL_Delay(static_cast<Uint32>(frameTime - Util::Time::GetDeltaTime()));
```

2024-02-22 07:41 UTC, Dragonfly911117 commented
Cool GitHub

2024-02-22 07:41 UTC, Dragonfly911117 approved these changes

2024-02-22 07:48 UTC, merged