Add a pivot for GameObject
ntut-open-source-club/practical-tools-for-simple-design pull request #113
Opened 2024-02-17 09:07 UTC by wj461

2024-02-17 13:46 UTC, ntut-rick commented on src/Util/GameObject.cpp
I'm not sure what this code can do. It seems like `m_Pivot` and `m_Transform.translation` serve the same function.

2024-02-17 13:47 UTC, ntut-rick commented on src/Util/GameObject.cpp
> +    m_Drawable->Draw(offsetTransform, m_ZIndex);
I'm not sure what this code can do. It seems like `m_Pivot` and `m_Transform.translation` serve the same function.

2024-02-22 09:46 UTC, Dragonfly911117 approved these changes
WOMM

2024-02-27 06:51 UTC, ntut-rick commented
I think this feature is not worthy to breaking the internal implement.
IMO here's a better way, but we are still discussing:
```diff
- void Draw(const Util::Transform &transform, const float zIndex,
-           const glm::vec2 &pivot) override;
+ void Draw(const glm::mat4 &mat4);
```

2024-02-27 06:51 UTC, ntut-rick requested changes
I think this feature is not worthy to breaking the internal implement.
IMO here's a better way, but we are still discussing:
```diff
- void Draw(const Util::Transform &transform, const float zIndex,
-           const glm::vec2 &pivot) override;
+ void Draw(const glm::mat4 &mat4);
```

2024-04-03 08:43 UTC, NOOBDY approved these changes

2024-04-03 08:55 UTC, ntut-rick approved these changes
![agreeGe](https://cdn.7tv.app/emote/60da25b89daf2660d850c4fc/1x.webp)

2024-04-03 09:01 UTC, merged