Keycode -> Util::Keycode
ntut-open-source-club/practical-tools-for-simple-design pull request #12
Opened 2023-05-31 15:54 UTC by ntut-rick

fix typo _from https://github.com/NOOBDY/practical-tools-for-simple-design/commit/3665f83b1a855987906858522079a9c6cf6c0fd9 in #7_

2023-05-31 16:35 UTC, NOOBDY commented
I think this is fixed in #9 ?

2023-05-31 16:51 UTC, ntut-rick commented
But we block it for other reasons. And we can split tasks as small as possible.

2023-06-01 04:35 UTC, Error0229 approved these changes

2023-06-01 04:48 UTC, x06lan commented on src/App.cpp
> +
You need to stop wick brainwash another people approval PR

2023-06-01 05:02 UTC, Error0229 commented on src/App.cpp
> +
This is coding style problem.

2023-06-01 05:05 UTC, NOOBDY commented on src/App.cpp
> +
> You need to stop wick brainwash another people approval PR

what?

2023-06-02 01:21 UTC, Dragonfly911117 reviewed
Don't think this PR is necessary but merge it if needed.

2023-06-02 01:39 UTC, NOOBDY commented
actually for my [`workflow`](https://github.com/NOOBDY/practical-tools-for-simple-design/tree/workflow) branch to succeed this needs to be merged

2023-06-02 02:10 UTC, Dragonfly911117 commented
Then, do it

2023-06-02 06:01 UTC, NOOBDY requested changes
Util::Keycode::ESCAPE

2023-06-02 06:44 UTC, NOOBDY approved these changes
LGTM

2023-06-02 06:44 UTC, merged