move sample to example
ntut-open-source-club/practical-tools-for-simple-design pull request #161
Opened 2024-03-28 08:22 UTC by NOOBDY

change the original executable to a library and move the sample code to `/example` folder

2024-03-31 16:32 UTC, ntut-rick reviewed
IWOMM

2024-04-01 05:15 UTC, Dragonfly911117 commented on CMakeLists.txt
> -    ${INCLUDE_DIR}/config.hpp
It's at line 59.

2024-04-01 05:24 UTC, Dragonfly911117 reviewed
So I was thinkg if we should separate `Tests` and `Example` related CMake configuations to each `CMakeLists.txt` in their directories and have `${REPO_ROOT}/CMakeLists.txt` add them.

2024-04-01 05:26 UTC, NOOBDY commented
I don't think it needs to be that complicated

2024-04-01 05:36 UTC, Dragonfly911117 requested changes

2024-04-01 05:36 UTC, Dragonfly911117 commented on CMakeLists.txt
> -    GTest::gtest_main
I think you forgot to put this back.
```suggestion
target_link_libraries(Tests
    GTest::gtest_main
```

2024-04-01 05:36 UTC, Dragonfly911117 commented on CMakeLists.txt
> +    PTSD
```suggestion
target_link_libraries(AudioTest
    PTSD
    GTest::gtest_main
```

2024-04-02 06:04 UTC, ntut-rick approved these changes

2024-04-02 13:06 UTC, Dragonfly911117 approved these changes

2024-04-02 13:42 UTC, merged