Set the icon with sdl2
ntut-open-source-club/practical-tools-for-simple-design pull request #173
Opened 2024-04-09 07:28 UTC by onon1101

2024-04-09 11:35 UTC, NOOBDY requested changes

2024-04-09 13:03 UTC, onon1101 commented
Do i need to push again ?

2024-04-09 13:04 UTC, onon1101 commented
i don't know why it's not pass in macOS

2024-04-09 14:31 UTC, NOOBDY commented
i have triggered a re-run for macos workflow

2024-04-09 16:31 UTC, ntut-rick commented on .gitignore
> +./**/.DS_Store
```suggestion
.DS_Store
```

2024-04-10 10:22 UTC, onon1101 commented
MR

2024-04-10 12:08 UTC, ntut-rick approved these changes
IWOMM

2024-04-11 04:16 UTC, Dragonfly911117 commented on include/Core/Context.hpp
> +    void SetWindowIcon(const std::string path);
Use const string ref saves resources.

2024-04-11 04:16 UTC, Dragonfly911117 commented on src/Core/Context.cpp
> +void Context::SetWindowIcon(const std::string path) {
Use const string ref saves resources.

2024-04-11 05:37 UTC, Dragonfly911117 approved these changes
LGTM&IWOMM

2024-04-11 05:37 UTC, NOOBDY approved these changes

2024-04-11 05:46 UTC, merged