Runtime config and small bug fix
ntut-open-source-club/practical-tools-for-simple-design pull request #174
Opened 2024-04-09 10:16 UTC by Dragonfly911117

Implement #153
Fix #167

2024-04-11 06:25 UTC, ntut-rick commented on include/Util/Config.hpp
> +}
null value and default value is indistinguishable

2024-04-29 11:59 UTC, onon1101 reviewed
不曉得是不是能從 `std::string` 改成 c17 的 `std::string_view`, 可能會對記憶體分配好一點？

2024-04-29 11:59 UTC, onon1101 commented on src/config.cpp
> +std::string PTSD_Config::TITLE = "Practice-Tools-for-Simple-Design";
```suggestion
std::string_view PTSD_Config::TITLE = "Practice-Tools-for-Simple-Design";
```

2024-04-29 11:59 UTC, onon1101 commented on include/config.hpp
> +    static std::string TITLE;
```suggestion
    static std::string_view TITLE;
```

2024-04-29 11:59 UTC, onon1101 commented on src/config.cpp
> +    TITLE = j["title"].get<std::string>();
```suggestion
    TITLE = j["title"].get<std::string_view>();
```

2024-04-29 12:00 UTC, onon1101 commented
並且在其他的地方以 `data()` 等方式存取, (具體可能要看 cpp 的文件)

2024-04-30 06:41 UTC, Dragonfly911117 commented on src/config.cpp
> +std::string PTSD_Config::TITLE = "Practice-Tools-for-Simple-Design";
Suggestion applied.

2024-05-02 04:33 UTC, ntut-rick requested changes

2024-05-02 04:33 UTC, ntut-rick commented on include/config.hpp
IMO static or singleton pattern is not necessary, just use normal class and provide a default global variable is fine.

2024-05-02 05:50 UTC, NOOBDY approved these changes

2024-05-02 05:52 UTC, ntut-rick approved these changes

2024-05-02 05:57 UTC, merged