Transform
ntut-open-source-club/practical-tools-for-simple-design pull request #29
Opened 2023-07-22 16:24 UTC by ntut-rick

2023-07-24 03:32 UTC, NOOBDY requested changes

2023-07-24 03:32 UTC, NOOBDY commented on include/Util/Transform.hpp
> +    Transform Scale(float x, float y) const { return Scale(glm::vec2(x,y)); }
I don't think overloading here is necessary, if users wanted to they can write their own helper functions

2023-07-24 03:32 UTC, NOOBDY commented on include/Util/Transform.hpp
> +    glm::mat3 m_mat3;
I think calling this `m_Data` or something would be better

2023-07-24 03:32 UTC, NOOBDY commented on include/Util/Transform.hpp
> +    Transform operator*(Transform const& other) { return Transform(m_mat3 * other.m_mat3); }
I still think this is a leaky abstraction

2023-08-03 14:00 UTC, NOOBDY requested changes

2023-08-12 12:08 UTC, NOOBDY commented
we should add functions for resetting value, something like `SetTranslation(glm::vec2)`

2023-08-12 14:01 UTC, NOOBDY requested changes
- [ ] Add Setter
- [ ] Add Readable Getter
- [ ] `const Transform &other`
- [ ] Remove mat3 API

2023-08-26 12:16 UTC, NOOBDY commented on include/Util/Transform.hpp
Maybe change the order to TRS?

2023-08-26 12:22 UTC, NOOBDY commented on src/Util/Transform.cpp
Pro tip:
you can use
```
// NOLINTBEGIN(readability-identifier-length)

// code goes here

// NOLINTEND(readability-identifier-length)
```

2023-08-26 12:25 UTC, NOOBDY commented on src/Util/Transform.cpp
> +    return radians >= 0 ? radians : radians + 4 * acos(0.0);
using `std::atan2` and `std::acos` would be more "C++" here

2023-08-26 12:26 UTC, NOOBDY requested changes

2023-08-26 12:26 UTC, NOOBDY commented on src/Util/Transform.cpp
> +    return radians >= 0 ? radians : radians + 4 * acos(0.0);
there are narrowing conversion warnings here

2023-08-26 12:39 UTC, NOOBDY requested changes
more things i noticed

2023-08-27 17:19 UTC, NOOBDY requested changes

2023-08-27 17:19 UTC, NOOBDY commented on src/Util/Transform.cpp
why didn't you use it here
`readability-identifier-length` and `readability-magic-numbers`

2023-08-27 17:19 UTC, NOOBDY commented on test/TransformTest.cpp
> +    EXPECT_NEAR(result + 4 * acos(0.0), expected, M_PI_TOLERANCE);
missed `std::` here

2023-08-27 18:10 UTC, ntut-rick commented on test/TransformTest.cpp
> +    EXPECT_NEAR(result, expected, M_PI_TOLERANCE * 1e+3F);
IDK, Maybe bc it have 1000x tolerance after 269.69 degrees rotation 🤷‍♀️

2023-09-02 08:44 UTC, NOOBDY submitted a review, later dismissed
LGTM

2023-09-11 05:57 UTC, NOOBDY requested changes

2023-09-11 05:57 UTC, NOOBDY commented on src/Util/Transform.cpp
> +        m_Mat3[2][0],   m_Mat3[2][1],  1.0f //
```suggestion
        m_Mat3[2][0],   m_Mat3[2][1],  1.0F //
```

2023-09-11 05:57 UTC, NOOBDY commented on src/Util/Transform.cpp
> +        m_Mat3[2][0],   m_Mat3[2][1],  1.0f //
```suggestion
        m_Mat3[2][0],   m_Mat3[2][1],  1.0F //
```

2023-09-11 05:57 UTC, NOOBDY commented on src/Util/Transform.cpp
> +// NOLINTBEGIN(readability-magic-numbers)
```suggestion
// NOLINTBEGIN(readability-identifier-length,readability-magic-numbers)
```

2023-09-11 05:57 UTC, NOOBDY commented on src/Util/Transform.cpp
> +// NOLINTEND(readability-magic-numbers)
```suggestion
// NOLINTEND(readability-identifier-length,readability-magic-numbers)
```

2023-09-13 14:25 UTC, Dragonfly911117 commented
The `add_compile_definitions(GLEW_NO_GLU)` option, which was adde in ea0ba3c,  in Dependencies.cmake is gone; and making it uncompile-able.

2023-09-13 14:28 UTC, Dragonfly911117 requested changes
everything else seems fine to me

2023-09-14 07:08 UTC, NOOBDY approved these changes

2023-09-18 03:24 UTC, Dragonfly911117 approved these changes
LGTM

2023-09-18 03:24 UTC, merged