Merge Drawable Class dev-branch to main repo
ntut-open-source-club/practical-tools-for-simple-design pull request #43
Opened 2023-10-01 18:32 UTC by ntut-rick

2023-10-01 18:36 UTC, NOOBDY commented
I don't think I should review my code

2023-10-01 18:46 UTC, ntut-rick commented
I can't review my PR, btw.

2023-10-02 04:38 UTC, Dragonfly911117 requested changes

2023-10-02 04:38 UTC, Dragonfly911117 commented on include/Core/Drawable.hpp
> +
Missed virtual destructor causes warning in the future

2023-10-02 04:38 UTC, Dragonfly911117 commented on include/Core/Texture.hpp
> +    GLuint GetTextureId() const { return m_TextureId; }
The getter should be above `Bind()`

2023-10-02 04:38 UTC, Dragonfly911117 commented on include/Util/Image.hpp
> +    static std::unique_ptr<Core::UniformBuffer<Core::Matrices>> s_UniformBuffer;
> Static members should be declared above normal members.

2023-10-02 04:38 UTC, Dragonfly911117 commented on include/Util/Text.hpp
> +    static std::unique_ptr<Core::UniformBuffer<Core::Matrices>> s_UniformBuffer;
> Static members should be declared above normal members.

2023-10-02 04:45 UTC, Dragonfly911117 commented on include/Core/Drawable.hpp
> +
```patch
Subject: [PATCH] Add a virtual destructor to Core::Drawable
---
Index: include/Core/Drawable.hpp
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/include/Core/Drawable.hpp b/include/Core/Drawable.hpp
--- a/include/Core/Drawable.hpp	(revision 15eb0de344348cd86453612a7b7d5d69f6267882)
+++ b/include/Core/Drawable.hpp	(date 1696221657870)
@@ -18,6 +18,7 @@
 ``` should work

2023-10-02 05:04 UTC, Dragonfly911117 commented on include/Core/Drawable.hpp
> +    virtual void Draw() = 0;
```suggestion
    virtual ~Drawable() = default;
    virtual void Draw() = 0;
```

2023-10-02 05:13 UTC, Dragonfly911117 approved these changes
LGTM

2023-10-02 05:13 UTC, merged