📝 Code Styles and Guidelines
ntut-open-source-club/practical-tools-for-simple-design pull request #82
Opened 2024-01-16 18:13 UTC by ntut-rick

Resolve #80

2024-01-17 15:10 UTC, Dragonfly911117 approved these changes
LGTM

2024-01-18 13:40 UTC, NOOBDY requested changes

2024-01-18 13:40 UTC, NOOBDY commented on .github/docs/Code-Styles-and-Guidelines.md
This could be placed under `docs` and turn into a Doxygen page

2024-01-19 14:19 UTC, ntut-rick commented on .github/docs/Code-Styles-and-Guidelines.md
I think this might be related to the structure of Doxygen and README documents. We (or I) need more time to discuss.

*My draft work:*
![doxygne screenshot](https://github.com/ntut-open-source-club/practical-tools-for-simple-design/assets/126899559/4a253654-07f9-42c0-acc2-65e55126d188)

2024-01-19 14:24 UTC, ntut-rick commented on .github/docs/Code-Styles-and-Guidelines.md
I mean we can delay this if merging the docs is important

2024-01-28 06:54 UTC, NOOBDY approved these changes

2024-01-28 06:56 UTC, merged