Add and fix Util doc
ntut-open-source-club/practical-tools-for-simple-design pull request #90
Opened 2024-02-01 14:03 UTC by Dragonfly911117

#72 
#48

2024-02-02 13:32 UTC, NOOBDY commented on include/Util/Transform.hpp
> +#endif /* UTIL_TRANSFORM_HPP */
i think this is caused by EOF linebreak

2024-02-03 07:20 UTC, NOOBDY requested changes
small typos

2024-02-03 07:20 UTC, NOOBDY commented on include/Util/Transform.hpp
> +     * @note The unit of rotataion is in radians not degrees.
```suggestion
     * @note The unit of rotation is in radians not degrees.
```

2024-02-03 07:20 UTC, NOOBDY commented on include/Util/Time.hpp
> +     * It is called by Cord::Context::Update(). The user is not recommanded to
```suggestion
     * It is called by Cord::Context::Update(). The user is not recommended to
```

2024-02-07 07:45 UTC, ntut-rick requested changes

2024-02-08 05:48 UTC, NOOBDY approved these changes

2024-02-08 09:15 UTC, NOOBDY approved these changes

2024-02-08 15:39 UTC, ntut-rick approved these changes

2024-02-08 15:40 UTC, merged